// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzvzsnwqdzfjfjultbjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6dnpzbndxZHpmamZqdWx0Ymp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MjUxODksImV4cCI6MjA2NzEwMTE4OX0.kRnI50wzVq_D-Mw2c2OjpG9LQtsCalIL7cgzhwawX6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});